CREATE TABLE REJECT_CREDITRISK (
    ALERTID NUMBER,
    LOANACCOUNTID NUMBER,
    RISKREASON VARCHAR2(200),
    RISKSCORE NUMBER,
    ALERTSTATUS VARCHAR2(20),
    REJECTREASON VARCHAR2(100)
);