CREATE TABLE REJECT_LOANACCOUNTS (
    LOANACCOUNTID NUMBER,
    APPLICATIONID NUMBER,
    APPROVEDAMOUNT NUMBER(10,2),
    INTERESTRATE NUMBER(5,2),
    ACCOUNTSTATUS VARCHAR2(20),
    REJECTREASON VARCHAR2(100)
);
drop table REJECT_LOANACCOUNTS;