CREATE TABLE REJECT_LOANAPPLICATION (
    APPLICATIONID NUMBER,
    CUSTOMERID NUMBER,
    LOANTYPE VARCHAR2(50),
    REQUESTEDAMOUNT NUMBER(10,2),
    APPLICATIONSTATUS VARCHAR2(20),
    REJECTREASON VARCHAR2(100)
);